export const fileDescriptions: { [key: string]: string } = {
  "app.log":
    "This log contains general application runtime information and events.",
  "combined.log":
    "Combined output from both the CLI and GUI logs, summarizing activities across interfaces.",
  "cycle.log":
    "This log records information about cycles record creation process.",
  "error.log":
    "Contains error messages and stack traces encountered during execution.",
  "errorFile.log":
    "Log of critical system errors and issues for diagnostic purposes.",
  "exit-summary.log":
    "A summary of the processes that occurred during the shutdown of the node.",
  "exit.log":
    "Logs related to the termination or exit of the node, including shutdown events.",
  "fatal.log":
    "Contains logs of fatal errors that led to critical failures in the system.",
  "main.log": "Centralized log for core processes and main node events.",
  "net.log":
    "Logs networking activity, including incoming and outgoing connections and network errors.",
  "out.log":
    "Contains standard output logs for application events, useful for debugging.",
  "p2p.log":
    "Logs peer-to-peer networking activity, including node connections and message exchanges.",
  "playback.log": "Records events related to playback operations.",
  "seq.log":
    "Sequential logs that record ordered events, useful for tracing the flow of operations.",
  "shardDump.log": "Detailed logs of shard related data.",
  "start-summary.log":
    "Information about the node startup. Contains the node start time.",
  "statsDump.log": "Contains statistics generated by the node.",
};
